### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Chifen-F** [nimmadev/pyrogram-add-member#5]
I appriciate your work,   Please  make it use only Phone number for authentication like here https://github.com/saifalisew1508/Telegram-Members-Adder.git Thanks ....
I have tried implimenting same trategy with Pyrogram, but I am just so much more into Telethon

If possible, just make this repo have just 2 python file(Manager.py and adder.py). Thanks again.....

**Comment by nimmadev** [comment]
U don't need api I'd and had just select no when making config
