### ISSUE TITLE
Problem adding with any id, error

### ISSUE THREAD

**Issue by yarinhalili** [nimmadev/pyrogram-add-member#7]
![test](https://user-images.githubusercontent.com/23079835/211691855-2d17ca18-e232-479c-a473-15efd8664995.png)
any id or username of groups that i try gives me the same error
Please help

**Comment by nimmadev** [comment]
Follow the guide 
Run login.py after joining group or to join group

**Comment by yarinhalili** [comment]
could not join maybe already in source group
PAM-Login-Signup - INFO - could not join maybe already in target group

**Comment by nimmadev** [comment]
> could not join maybe already in source group PAM-Login-Signup - INFO - could not join maybe already in target group

Yes if already join it refresh the session so just use get_data.py nos

**Comment by nimmadev** [comment]
> could not join maybe already in source group PAM-Login-Signup - INFO - could not join maybe already in target group

updated the project so it ell what to do and ask if you wsh to continue

**Comment by yarinhalili** [comment]
okay ♥ btw it was my mistake
For knowledge ,I tried troubleshoot the first problem and instead of writing username, wrote the url itself and thats what caused the error
